version: '3.5'

services:

  web:
    container_name: web
    image: nginx:alpine
    #build:
    #  context: $PWD/dockerfile
    #  dockerfile: web.Dockerfile
    depends_on:
      # `app`Because the service (container) needs to be started first`depends_on`Is specified
      - frontend
      - backend
    ports:
      #Port mapping:"Host OS port:container(Nginx)Port"
      - "80:80"
    #user: "${USER_ID}:${GROUP_ID}"
    volumes:
      #volume mount:"Host OS path:Path in the container"
      - ./.bashrc:/root/.bashrc
      #- ./web/html:/etc/nginx/html
      - ./web/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  frontend:
        image: vue_frontend
        container_name: front
        build:
            context: .
            dockerfile: ./dockerfile/frontend.Dockerfile
        networks:
            - nginx_network
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        ports:
            - 8080:8080
        command: /bin/sh -c "npm run serve"
        

  backend:
    restart: always
    container_name: was
    image: gunicorn-fastapi
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: ./dockerfile/backend.Dockerfile
    ports:
      - 8001:5000
    networks:
      - nginx_network

    #For example, if you want to edit the source code in real time`volumes`Convenient to mount with
    volumes:
      - ./.bashrc:/root/.bashrc
      - ./fastapi/app:/code/app
    
    # command:
    #   - "uvicorn app.main:app --reload --host 0.0.0.0 --port 5000"

networks:
  nginx_network:
    driver: bridge

